import type { Metadata } from "next";
import { Actor } from "next/font/google";
import "./globals.css";
import { Providers } from "../../providers";
import Link from "next/link";

const actor = Actor({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-actor",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${actor.variable} antialiased`}>
        <header className="flex justify-between items-center p-8 bg-white rounded-3xl ">
          <Link href='/' className="text-4xl">Footbally.</Link>
          <div className="flex gap-2">
            <Link href='/articles'>News</Link>
            <Link href='/register'>Register</Link>
            <Link href='/login'>Login</Link>
          </div>
        </header>
        <Providers>
          {children}
        </Providers>
        <footer><p>FOOTER</p></footer>
      </body>
    </html>
  );
}
