import type { Metadata } from "next";
import {Actor} from "next/font/google";
import "./globals.css";

const actor = Actor({
  subsets: ["latin"],
  weight: ['400'],
  variable:'--font-actor'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${actor.variable} ${actor.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
