
import type { Metadata } from "next";
import { Actor } from "next/font/google";
import "./globals.css";
import { Providers } from "../../providers";
import Header from "../../components/Header";
import { Toaster } from 'sonner'

const actor = Actor({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-actor",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${actor.variable} antialiased min-h-screen flex flex-col `}>
        <Providers>
          <Header></Header>
          {children}
        </Providers>
        <Toaster position="top-right" richColors></Toaster>
        <footer className="bg-black py-20 text-center text-white"><p>FOOTER</p></footer>
      </body>
    </html>
  );
}
