name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged
        ports:
          - 4000:4000
          - 3000:3000

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/footbally-backend:latest .
          docker push $DOCKERHUB_USERNAME/footbally-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/footbally-frontend:latest ./frontend
          docker push $DOCKERHUB_USERNAME/footbally-frontend:latest
